### ISSUE TITLE
Plugin not rendering icon

### ISSUE THREAD

**Issue by bolte-io** [aaroniker/figma-icns-ico-generator#13]
Using Figma desktop or within browser, the plugin is just displaying a spinning circle and not doing anything.

Previously I had used this to make a bunch of icons.
Tried this on latest Figma desktop and within the browser (Edge)

![image](https://user-images.githubusercontent.com/51535687/119412294-9185df80-bce3-11eb-9633-cebddeb94b89.png)
It just get's stuck on this

**Comment by aaroniker** [comment]
Fixed.
